// Word + TLD plays (5 letters max, prefix + TLD = valid word)

const domains = [
  // 2+2 = 4 letter words (prefix.tld)
  "ab.bey", "ac.id", "ad.or", "ag.ent", "al.arm", "am.ount", "an.ger", "ar.mor", "as.phalt", "at.las",
  "aw.l", "ax.is", "ba.con", "be.d", "bi.ble", "bo.d", "bu.d", "by.product", "ca.b", "ce.ment",
  "ch.ain", "ci.der", "co.b", "cr.ew", "cu.b", "cy.cle", "da.m", "de.ck", "di.sh", "do.b", "du.ck",
  "dy.er", "ea.gle", "ed.ge", "ef.fect", "el.bow", "em.bed", "en.code", "ep.och", "er.ase", "es.cape",
  "et.ernal", "ev.il", "ex.it", "fa.cade", "fe.ather", "fi.nch", "fl.ame", "fo.lk", "fr.ame",
  "fu.el", "ga.ble", "ge.ese", "gi.ft", "go.b", "gr.ape", "gu.ess", "ha.m", "he.el", "hi.de",
  "ho.se", "hu.m", "hy.drant", "id.ler", "if.else", "im.bed", "in.put", "ir.on", "it.ch",
  "ja.m", "je.t", "ji.b", "jo.b", "ju.mper", "ka.yak", "ke.el", "ki.t", "kn.ife", "ko.a",
  "la.b", "le.ash", "li.b", "lo.b", "lu.b", "ly.ric", "ma.p", "me.sh", "mi.c", "mo.d",
  "mu.d", "my.th", "na.v", "ne.t", "ni.b", "no.d", "nu.b", "ny.mp", "ob.server", "oc.topus",
  "od.ometer", "of.fset", "ok.ra", "ol.ive", "om.eter", "on.ion", "op.era", "or.b", "os.ter",
  "ot.ter", "ov.en", "ox.ymoron", "pa.n", "pe.ck", "pi.ano", "pl.ane", "po.et", "pr.ism",
  "pu.pa", "qu.ilt", "ra.n", "re.f", "ri.b", "ro.d", "ru.b", "sa.n", "se.t", "sh.ell",
  "si.de", "sk.ull", "sl.ime", "sn.ail", "so.ap", "sp.oon", "st.ick", "su.m", "sw.ord",
  "ta.p", "te.m", "ti.n", "to.p", "tr.ack", "tu.n", "tw.ig", "ul.cer", "un.ion", "up.set",
  "ur.ine", "us.able", "ut.ensil", "va.n", "ve.t", "vi.per", "vo.lume", "vu.lt", "wa.nt",
  "we.b", "wh.ip", "wi.n", "wo.b", "wr.ist", "xe.ran", "ya.cht", "ye.ar", "yo.yo", "ze.ro",
  // 3+2 = 5 letter words
  "ab.used", "ac.orns", "ad.apts", "ag.gres", "al.cohol", "am.bush", "an.cient", "ar.cade",
  "as.phalt", "at.om", "au.tumn", "av.ocado", "aw.ard", "ax.es", "ba.bies", "be.droom",
  "bi.cycle", "bo.ttle", "bu.tton", "by.passed", "ca.bbage", "ce.iling", "ch.icken", "ci.gar",
  "co.mpass", "cr.acker", "cu.cumber", "cy.mbal", "da.ncing", "de.licious", "di.nner",
  "do.cker", "du.cket", "dy.ing", "ea.gles", "ed.itor", "ef.fort", "el.ephant", "em.bassy",
  "en.velope", "ep.sode", "er.ror", "es.cape", "et.ernal", "ev.ening", "ex.ample", "fa.ces",
  "fe.ather", "fi.bre", "fl.ower", "fo.otball", "fr.iend", "fu.neral", "ga.rage",
  "ge.ometry", "gi.raffe", "go.at", "gr.oup", "gu.itar", "ha.mmer", "he.ader", "hi.ppo",
  "ho.pper", "hy.drant", "i.llness", "im.porter", "in.sect", "io.dine", "ir.on", "i.ron",
  "it.em", "ja.cks", "je.lly", "jo.urnal", "ju.nior", "ka.yaks", "ke.ys", "ki.ll",
  "kn.ow", "ko.ala", "la.bs", "le.mon", "li.brary", "lo.gic", "lu.nch", "ly.ing",
  "ma.nage", "me.dia", "mi.nute", "mo.nkey", "mu.sic", "my.th", "na.vy", "ne.d",
  "ni.ght", "no.m", "nu.t", "ny.mp", "o.asis", "ob.ject", "oc.ulus", "od.d",
  "of.fer", "ok.ay", "ol.d", "om.elet", "on.ion", "op.era", "or.b", "os.car",
  "ot.ter", "ov.er", "ox.ygen", "pa.st", "pe.ach", "pi.ano", "pl.ace", "po.et",
  "pr.int", "pu.ppy", "qu.iet", "ra.bbit", "re.d", "ri.bbon", "ro.cket", "ru.n",
  "sa.lad", "se.a", "sh.ell", "si.de", "sk.y", "sl.ate", "sm.oke", "sn.ake",
  "so.ap", "sp.oon", "st.ar", "su.n", "sw.ing", "ta.ble", "te.n", "ti.n",
  "to.m", "tr.ee", "tw.ig", "ul.cer", "un.der", "up.on", "ur.ban", "us.a",
  "ut.ah", "va.n", "ve.t", "vi.b", "vo.w", "vu.l", "wa.ll", "we.b",
  "wh.ip", "wi.ll", "wo.ol", "wr.ong", "xe.non", "ya.cht", "ye.ar", "yo.ga",
  "ze.bra",
  // 1+3 = 4 letter words
  "b.ook", "c.ook", "f.ook", "h.ook", "l.ook", "p.ook", "s.ook", "t.ook", "w.ook",
  "b.ath", "c.ath", "f.ath", "g.ath", "h.ath", "l.ath", "m.ath", "p.ath", "s.ath",
  "b.ush", "c.ush", "f.ush", "g.ush", "h.ush", "l.ush", "p.ush", "r.ush", "t.ush",
  "b.and", "c.and", "f.and", "g.and", "h.and", "l.and", "m.and", "p.and", "s.and",
  "b.ank", "c.ank", "f.ank", "g.ank", "h.ank", "l.ank", "m.ank", "p.ank", "s.ank",
  "b.ell", "c.ell", "f.ell", "g.ell", "h.ell", "l.ell", "m.ell", "p.ell", "s.ell",
  "b.ill", "c.ill", "f.ill", "g.ill", "h.ill", "l.ill", "m.ill", "p.ill", "s.ill",
  "b.ull", "c.ull", "f.ull", "g.ull", "h.ull", "l.ull", "m.ull", "p.ull", "s.ull",
  "b.owl", "c.owl", "f.owl", "h.owl", "j.owl", "p.owl", "t.owl",
  "b.ond", "c.ond", "f.ond", "g.ond", "h.ond", "l.ond", "m.ond", "p.ond", "r.ond",
  "b.ald", "c.ald", "f.ald", "g.ald", "h.ald", "l.ald", "m.ald", "p.ald", "s.ald",
  "b.old", "c.old", "f.old", "g.old", "h.old", "l.old", "m.old", "p.old", "s.old",
  "b.ild", "c.ild", "f.ild", "g.ild", "h.ild", "l.ild", "m.ild", "p.ild", "s.ild",
  // 2+3 = 5 letter words
  "ab.ove", "ad.apt", "ag.ain", "al.oud", "am.ide", "an.ger", "ap.art", "ar.ound",
  "as.ide", "at.ome", "aw.ake", "ba.sic", "be.t", "bi.ble", "bo.ard", "bu.ild",
  "ca.re", "ce.il", "ch.ip", "ci.vil", "co.de", "cr.own", "cu.ite", "cy.cus",
  "da.nce", "de.al", "di.g", "do.or", "du.ty", "dy.ne", "ea.t", "ef.fort", "el.even",
  "em.pty", "en.d", "ep.ic", "er.ase", "es.cape", "et.ernal", "ev.il", "ex.it",
  "fa.n", "fe.ather", "fi.nal", "fl.y", "fo.rum", "fr.ame", "fu.n", "ga.m",
  "ge.n", "gi.st", "go.n", "gr.ape", "gu.ess", "ha.n", "he.l", "hi.t",
  "ho.m", "hu.m", "hy.d", "i.d", "if.y", "in.d", "io.n", "ir.n", "is.le",
  "ja.b", "je.lly", "jo.b", "ju.n", "ke.l", "ki.d", "kn.ow", "ko.a", "la.n",
  "le.t", "li.f", "lo.b", "lu.n", "ly.n", "ma.n", "me.t", "mi.n", "mo.d",
  "mu.n", "my.n", "na.v", "ne.t", "ni.n", "no.n", "nu.n", "ny.n",
];

console.log(domains.slice(0, 500).join("\n"));
