/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Test function to verify NAPI bindings work */
export declare function plus100(input: number): number

/** Property value tag for binary encoding */
export declare const enum PropValueTag {
  Null = 0,
  Bool = 1,
  I64 = 2,
  F64 = 3,
  String = 4,
  VectorF32 = 5
}

/** Get RayDB version */
export declare function version(): string
